spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/apca?autoReconnect=true
    username: lamis
    password: lamis
    #Str0ngAdmInP@ssw0rd
     #ddd_liberia
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: dddapp.lib@gmail.com
    password: "dddapp1@"
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.auth: true
      jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect






